// Code generated by typegen/main.go. DO NOT EDIT.

import type { ConnectionType } from "./typesGenerated";

// Display names of the connection types the `type` filter accepts. Record
// fails to compile if a ConnectionType has no entry.
export const connectionTypeDisplayNames: Record<ConnectionType, string> = {
	jetbrains: "JetBrains",
	port_forwarding: "Port Forwarding",
	reconnecting_pty: "Web Terminal",
	ssh: "SSH",
	tunnel: "Tunnel",
	unknown: "Unknown",
	vscode: "VS Code",
	workspace_app: "Workspace App",
};
